---
behaviors:
  AgentController:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 3072
      learning_rate: 0.00005
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
    max_steps: 2500000
    time_horizon: 128
    summary_freq: 10000

